CRUD-MVC-EF/Models/Contacto.cs
using System.ComponentModel.DataAnnotations;

namespace CRUD_MVC_EF.Models
{
    public class Contacto
    {
        [Key] //Si tiene la palabra Id entity framewor detecta que es una clave primaria automaticamente
        //pero se pued ecolocar explicitamete que es una key
        public int IdContacto { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El telefono es obligatorio")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "El email es obligatorio")]
        public string Email { get; set; }
        public DateTime FechaCreacion { get; set; }
    }
}

CRUD-MVC-EF/Models/ErrorViewModel.cs
namespace CRUD_MVC_EF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD-MVC-EF/Controllers/InicioController.cs
using CRUD_MVC_EF.Datos;
using CRUD_MVC_EF.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CRUD_MVC_EF.Controllers
{
    public class InicioController : Controller
    {
        private readonly DBContext _dbContext;
        public InicioController(DBContext dBContext)
        {
            _dbContext = dBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _dbContext.Contacto.ToListAsync());
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Contacto contacto)
        {
            if (ModelState.IsValid) {

                contacto.FechaCreacion = DateTime.Now;
                _dbContext.Contacto.Add(contacto);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View();
        }


        public IActionResult Editar(int id)
        {
            if (id == 0 || id == null) {
                return NotFound();
            }

            var contacto = _dbContext.Contacto.Find(id);

            if (contacto == null) {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            if (ModelState.IsValid)
            {

                _dbContext.Contacto.Update(contacto);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View();
        }

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var contacto = _dbContext.Contacto.Find(id);

            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        public IActionResult Borrar(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var contacto = _dbContext.Contacto.Find(id);

            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarContacto(Contacto contacto)
        {

            //var contacto = _dbContext.Contacto.FindAsync(IdContacto);
            
            if (contacto == null)
            {
                return View();
            }

            _dbContext.Remove(contacto);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD-MVC-EF/Views/Inicio/Borrar.cshtml
@model CRUD_MVC_EF.Models.Contacto
@{
    ViewData["Title"] = "Borrar Contacto";
}

<h1 class="text-center">
    Contacto con .NET 8 (.NET CORE MVC)
</h1>


<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <div class="text-white">
                    <strong>Borrar Contacto</strong>
                </div>

            </div>
            <div class="card-body">
                <form asp-action="Borrar">

                    @* Id oculto del usuario *@
                    <input asp-for="IdContacto" type="hidden" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" readonly />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" readonly />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" readonly />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="FechaCreacion" class="control-label"></label>
                        <input asp-for="FechaCreacion" class="form-control" readonly />
                        <span asp-validation-for="FechaCreacion" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-secondary d-block mx-auto">
                            <i class="fa fa-user-plus" aria-hidden="true"></i> Borrar
                        </button>
                    </div>
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>

CRUD-MVC-EF/Views/Inicio/Crear.cshtml
@model CRUD_MVC_EF.Models.Contacto
@{
    ViewData["Title"] = "Crear Nuevo Contacto";
}

<h1 class="text-center">
    Contacto con .NET 8 (.NET CORE MVC)
</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <div class="text-white">
                    <strong>Crear Contacto Nuevo</strong>
                </div>

            </div>
            <div class="card-body">
                <form asp-action="Crear" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label" ></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-secondary d-block mx-auto">
                            <i class="fa fa-user-plus" aria-hidden="true"></i> Crear Usuario
                        </button>
                    </div>
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>

CRUD-MVC-EF/Views/Inicio/Detalle.cshtml
@model CRUD_MVC_EF.Models.Contacto
@{
    ViewData["Title"] = "Detalle de Contacto";
}

<h1 class="text-center">
    Contacto con .NET 8 (.NET CORE MVC)
</h1>


<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <div class="text-white">
                    <strong>Detalle de Contacto</strong>
                </div>

            </div>
            <div class="card-body">
                
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong> @Html.DisplayFor(m => m.Nombre) </li>
                    <li class="list-group-item"><strong>Telefono: </strong> @Html.DisplayFor(m => m.Telefono) </li>
                    <li class="list-group-item"><strong>Email: </strong> @Html.DisplayFor(m => m.Email) </li>
                    <li class="list-group-item"><strong>Fecha de Creacion: </strong> @Html.DisplayFor(m => m.FechaCreacion) </li>
                </ul>

                <a asp-controller="Inicio" asp-action="Index" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>

CRUD-MVC-EF/Views/Inicio/Editar.cshtml
@model CRUD_MVC_EF.Models.Contacto
@{
    ViewData["Title"] = "Editar Contacto";
}

<h1 class="text-center">
    Contacto con .NET 8 (.NET CORE MVC)
</h1>


<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <div class="text-white">
                    <strong>Editar Contacto</strong>
                </div>

            </div>
            <div class="card-body">
                <form asp-action="Editar" method="post">

                    @* Id oculto del usuario *@
                    <input asp-for="IdContacto" type="hidden" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingresa el Nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingresa el Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button type="submit" class="btn btn-secondary d-block mx-auto">
                            <i class="fa fa-user-plus" aria-hidden="true"></i> Aceptar Cambios
                        </button>
                    </div>

                    <input asp-for="FechaCreacion" type="hidden" />
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>

CRUD-MVC-EF/Views/Inicio/Index.cshtml
@model IEnumerable<CRUD_MVC_EF.Models.Contacto>
@{
    ViewData["Title"] = "Lista de Contactos";
}

<h1 class="text-center">
    Contacto con .NET 8 (.NET CORE MVC)
</h1>

<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a asp-action="Crear" asp-controller="Inicio" class="btn btn-secondary d-block btn-lg mx-auto">
            <i class="fa fa-plus" aria-hidden="true"></i> Nuevo Usuario
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <div class="text-white">
                    <strong>Lista de Usuarios</strong>
                </div>
               
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table-bordered table" id="tblUsuarios" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.IdContacto)</th>
                                    <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                                    <th>@Html.DisplayNameFor(m => m.Email)</th>
                                    <th>@Html.DisplayNameFor(m => m.FechaCreacion)</th>
                                    <th>Acciones</th>
                                </tr>
                            <tbody class="text-center">
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@Html.DisplayFor(m => item.IdContacto)</td>
                                        <td>@Html.DisplayFor(m => item.Nombre)</td>
                                        <td>@Html.DisplayFor(m => item.Telefono)</td>
                                        <td>@Html.DisplayFor(m => item.Email)</td>
                                        <td>@Html.DisplayFor(m => item.FechaCreacion)</td>
                                        <td>
                                            <a class="btn btn-warning" asp-action="Editar" asp-route-id="@item.IdContacto">
                                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                                            </a>
                                            <a class="btn btn-secondary" asp-action="Detalle" asp-route-id="@item.IdContacto">
                                                <i class="fa fa-info-circle" aria-hidden="true"></i> Detalle
                                            </a>
                                            <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.IdContacto">
                                                <i class="fa fa-trash" aria-hidden="true"></i> Borrar
                                            </a>
                                        </td>
                                    </tr>
                                    }
                            </tbody>
                            </thead>
                        </table>
                    }
                    else
                    {
                        <p class="text-white">No hay registros</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CRUD-MVC-EF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_MVC_EF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_MVC_EF.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">CRUD_MVC_EF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_MVC_EF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>